### ISSUE TITLE
Provide instructions for browser and system usage

### ISSUE THREAD

**Issue by Manouchehri** [equalitie/HTTPS-Proxy#1]
I'm going to do this task myself; I'm writing down so it don't forget!

The proxy can quite easily be controlled with @FelisCatus' SwitchyOmega, which should eliminate any concerns regarding usability (it's two clicks to turn off a rule, same a HTTPS Everywhere). Also, I'm planning trying to get it working to redirect all HTTP traffic transparently with `iptables`.

**Comment by chaoticsmol** [comment]
You may be interested in what's going on in an experimental branch:
https://github.com/equalitie/HTTPS-Proxy/tree/limit-proxy

**Comment by Manouchehri** [comment]
Thanks.
